//
//  AppConstants.swift
//  MoTiv
//
//  Created by IOS on 27/11/18.
//  Copyright © 2018 MoTiv. All rights reserved.
//

import Foundation
import UIKit

//MARK: **** App Delegate ****
let appDelegate = UIApplication.shared.delegate as! AppDelegate


//MARK: **** SIGNUP ARRAY ****
var organiserTitleArray = ["FULL NAME", "ORGANISER USERNAME", "EMAIL ADDRESS", "PHONE NUMBER (FOR ENQUIRIES)", "PASSWORD", "CONFIRM PASSWORD", "ABOUT YOU (BIO)"]
var organiserPlaceholderArray = ["ENTER FULL NAME", "ENTER ORGANISER USERNAME", "ENTER EMAIL ADDRESS", "ENTER PHONE NUMBER", "ENTER PASSWORD", "ENTER CONFIRM PASSWORD", "ENTER DETAILS OF YOUR ORGANISATIONS AND YOUR EVENTS"]
let repeatArray = ["One Time","Weekly","Fortnightly","Monthly"]
let repeatIdArray = ["one_day","weekly","2_weekly","monthly"]
var dressCodeArray = ["Casual", "Formals"]
var idRequiredArray = ["Yes", "No"]

var BASE_URL2 = "http://1.6.98.139/webservices/sim_admin/public/api/v2/"
var BASE_URL = "http://1.6.98.139/webservices/sim/public/api/v2/"
var IMAGE_URL = "http://1.6.98.139/webservices/sim_admin/public"

//MARK: **** GOOGLE API KEY ****
let kGoogleKey = "AIzaSyB2ynyshHO_xofMn0oR9IBxvSQDrfXUwVs"

//MARK: **** Cell Identifies ****
let kTextFieldCell = "TextFieldCell"
let kTextViewCell = "TextViewCell"
let kEventCell = "EventCell"
let kCategoryCell = "CategoryCell"
let kUserCell = "UserCell"
let kCommentCell = "CommentCell"
let kAddCommentCell = "AddCommentCell"
let kPostSectionCell = "PostSectionCell"
let kTicketCell = "TicketCell"
let kSalesSummaryCell = "SalesSummaryCell"
let kCheckInSummaryCell = "CheckInSummaryCell"
let kCheckInCell = "CheckInCell"
let kAddGuestCell = "AddGuestCell"
let kGuestCell = "GuestCell"
let kNotificationCell = "NotificationCell"
let kCheckinEventCell = "CheckinEventCell"
let kGuestListcell = "GuestListcell"
let kProfileCell = "ProfileCell"
let kProfileCell1 = "ProfileCell1"
let kInviteUserCell = "InviteUserCell"
let kMyTicketCell = "MyTicketCell"
let kU_HomeCell = "U_HomeCell"
let kSongAlbumCell = "SongAlbumCell"
let kSectionCell = "SectionCell"
let kUserEventCell = "UserEventCell"
let kSendMessageCell = "SendMessageCell"
let kReceiveMessageCell = "ReceiveMessageCell"
let kSearchEventCell = "SearchEventCell"
let kPendingSearchFriendCell = "PendingSearchFriendCell"
let kSearchFriendCell = "SearchFriendCell"
let kInboxCell = "InboxCell"
let kSelectTicketCell = "SelectTicketCell"
let kTicketDetailsCell = "TicketDetailsCell"
let kSelectCardCell = "SelectCardCell"
let kSelectCardCellHeader = "SelectCardCellHeader"
let kBlockedUSerTableViewCell = "BlockedUSerTableViewCell"
let kInterestCell = "InterestCell"
let kTicketDataCell = "TicketDataCell"
let kTicketSoldCell = "TicketSoldCell"
let kTotalCheckinCell = "TotalCheckinCell"
let kCheckinDataCell = "CheckinDataCell"


//MARK: **** Storyboard Identifiers ****
let kLoginVC = "LoginVC"
let kTabBarVC = "TabBarVC"
let kO_HomeVC = "O_HomeVC"
let kEventDetails = "EventDetailVC"
let kDirectionVC = "DirectionVC"
let kUserListVC = "UserListVC"
let kViewPostVC = "ViewPostVC"
let kPostCommentsVC = "PostCommentsVC"
let kScanTicketVC = "ScanTicketVC"
let kAddPostVC = "AddPostVC"
let kOCreateMainVC = "O_CreateMainVC"
let kAddImageVC = "AddImageVC"
let kAddNameVC = "AddNameVC"
let kAddLocationVC = "AddLocationVC"
let kAddDateTimeVC = "AddDateTimeVC"
let kAddDetailsVC = "AddDetailsVC"
let kAddTicketsVC = "AddTicketsVC"
let kCreateTicketVC = "CreateTicketVC"
let kViewMotivVC = "ViewMotivVC"
let kEventMenuVC = "EventMenuVC"
let kMainGuestListVC = "MainGuestListVC"
let kCheckInVC = "CheckInVC"
let kDashBoardVC = "DashBoardVC"
let kAddGuestVC = "AddGuestVC"
let kGuestListVC = "GuestListVC"
let kcreateGuestListVC = "createGuestListVC"
let kSettingVC = "SettingVC"
let kHelpVC = "HelpVC"
let kPopOverVC = "PopOverVC"
let kDescriptionVC = "DescriptionVC"
let kInviteUserVC = "InviteUserVC"
let kU_TabbarVC = "U_TabbarVC"
let kTicketDetailsVC = "TicketDetailsVC"
let kAboutYouVC = "AboutYouVC"
let kSelectCategoryVC = "SelectCategoryVC"
let kReferalCodeVC = "ReferalCodeVC"
let kWelcomeVC = "WelcomeVC"
let kU_HomeVC = "U_HomeVC"
let kU_HomeFilterVC = "U_HomeFilterVC"
let kFindMotivVC = "FindMotivVC"
let kChatVC = "ChatVC"
let kInboxVC = "InboxVC"
let kMyProfileVC = "MyProfileVC"
let kSearchProfileFriendsVC = "SearchProfileFriendsVC"
let kUserChangePasswordVC = "UserChangePasswordVC"
let kViewProfileVC = "ViewProfileVC"
let kSelectPaymentMethodVC = "SelectPaymentMethodVC"
let kSelectCardVC = "SelectCardVC"
let kChnagePasswordVC = "ChnagePasswordVC"
let kMyTicketsVC = "MyTicketsVC"
let kTermConditionVC = "TermConditionVC"
let kSelectTicketVC = "SelectTicketVC"
let kBlockedUsersVC = "BlockedUsersVC"
let kSettingsVC = "SettingsVC"
let kInterestsVC = "InterestsVC"
let kEditProfileVC = "EditProfileVC"
let kSubCategoryVC = "SubCategoryVC"
let kAddFriendVC = "AddFriendVC"
let kReferralInnerVC = "ReferalCodeInnerVC"
let kSelectUserTypeVC = "SelectUserTypeVC"
let kNameVC = "NameVC"
let kUsernameVC = "UsernameVC"
let kEmailVC = "EmailVC"
let kProfilePictureVC = "ProfilePictureVC"
let kDOBVC = "dateOfBirthVC"
let kPasswordVC = "PasswordVC"
let kAddCategoryVC = "AddCategoryVC"



//MARK: **** Titles ****
let kForgotPassword = "FORGOT PASSWORD"
let kSignup = "SIGNUP"
let kSelectUserType = "SELECT USER TYPE"
let kMyEvents = "MY EVENTS"
let kGetDirections = "GET DIRECTIONS"
let kAttending = "ATTENDING"
let kPosts = "POSTS"
let kScanTicket = "SCAN TICKET"
let kCreateEvent = "CREATE EVENT"
let kAddTicket = "ADD TICKET"
let kCreateMoTiv = "CREATE MOTIV"
let kCheckIn = "CHECK IN"
let kDashboard = "DASHBOARD"
let kGuestList = "GUEST LIST"
let kGuestListName = "GUEST LIST NAME"
let kAddGuest = "ADD GUEST"
let kCreatGuestList = "CREATE GUEST LIST"
let kEditProfile = "EDIT PROFILE"
let kPromotionPackages = "PROMOTION PACKAGES"
let kNotifications = "NOTIFICATIONS"
let kSettings = "SETTINGS"
let kChangePassword = "CHANGE PASSWORD"
let kHelp = "HELP"
let kContactus = "CONTACT US"
let kTerms = "TERMS & CONDITIONS"
let kTickets = "TICKETS"
let kFilter = "FILTER"
let kInbox = "INBOX"
let kFindMoTiv = "FIND MOTIV"
let kSelectTickets = "SELECT TICKETS"
let kBuyNow = "BUY NOW"
let kSelectPaymentMethod = "SELECT PAYMENT METHOD"
let kSelectCard = "SELECT CARD"
let kMyProfile = "MY PROFILE"
let kBlockedUsers = "BLOCKED USERS"
let kViewProfile = "VIEW PROFILE"
let kHelloUser = "HELLO USERNAME"
let kAddFriend = "ADD FRIEND"
let kComments = "COMMENTS"

//MARK: **** TextView Placeholders ****
let kAboutYou = "ENTER DETAILS OF YOUR ORGANISATIONS AND YOUR EVENTS"
let kEnterComment = "ENTER COMMENT"
let kEnterDescription = "ENTER DESCRIPTION"
let kEnterEventDescription = "ENTER EVENT DESCRIPTION"
let kEventDescription = "EVENT DESCRIPTION"
let kTicketDescription = "TICKET DESCRIPTION"
let kContactDescription = "TYPE YOUR QUESTIONS HERE AND WE WILL RESPOND TO YOUR EMAIL ADDRESS"


//MARK: **** Alert titles and Buttons ****
let kSuccess = "SUCCESS"
let kOkay = "OKAY"
let kCancel = "CANCEL"
let kOpenMail = "OPEN MAIL"
let kYes = "YES"
let kNo = "NO"
let kShareMotiv = "SHARE MOTIV"
let kReset = "RESET"
let kSkip = "SKIP"
let kOpenEmail = "OPEN EMAIL"
let kError = "ERROR"
let kDelete = "Delete"
let kLoginNow = "LOGIN NOW"

//MARK: **** Alerts ****
let kGalleryAlert = "Please enable photos from your settings"
let kCameraAlert = "Please enable camera from your settings"
let kForgotAlert = "Forgot Password link has been sent to your registered email address"
let kSignupAlert = "you have successfully signed up. please verify your email"
let kCloseSaleAlert = "Are you sure you want to close the sale for this event?"
let kAddGuestSuccess = "A confirmation email has been sent to your guest"
let kCreateEventAlert = "event submitted to admin. it will be shown to users once admin approve the event."
let kProfileUpdateAlert = "profile details updated successfully"
let kEventUpdateAlert = "Event Updated Successfully"
let kPasswordChangeAlert = "password changed successfully"
let kLogoutAlert = "are you sure \nyou want to logout ?"
let kUserCreateMoTivAlert = "you have successfully created a motiv"
let kSignUpAlert = "ADD INFO TO YOUR BIO"
let kAboutYouAlert = "TO DISCOVER YOUR MOTIV PLEASE TELL US SOME OF YOUR INTEREST"
let kAllDoneAlert = "ALL DONE, PLEASE VERIFY YOUR EMAIL ADDRESS TO CREATE YOUR MOTIV"
let kChangePasswordAlert = "PASSWORD CHANGED SUCCESSFULLY"
let kPaymentSucess = "tickets saved in your tickets section"
let kAddFriendAlert = "Are you sure you want to send friend request?"
let kAddFriendSuccessAlert = "Friend Request sent successfully"
let kErrorMessage = "Something went wrong !"
let kCameraMessage = "Please provide access to Camera from settings"
let kGalleryMessage = "Please provide access to Gallery from settings"
let kLocationMessage = "Please enable location access from settings"
let kEmailValidation = "Please enter valid email address"
let kPasswordValidation = "Password must be atleast 6 characters long"
let kNewPasswordValidation = "New password must be atleast 6 characters long"
let kConfirmPasswordValidation = "Confirm Password does not match"
let kTermsValidation = "Please agree terms and conditions"
let kFirstNameValidation = "First Name must be atleast 2 characters long"
let kLastNameValidation = "Last Name must be atleast 2 characters long"
let kImageValidation = "Please add image/ video"
let kMainValidation = "Please select primary image/ video to show"
let kVideoLimt = "You can upload video of 1 minute"
let kEventNameValidation = "Event name must be atleast 2 characters long"
let kURLValidation = "Please enter valid URL"
let kPublicValidation = "Please select public categories for the event"
let kMusicValidation = "Please select music category for the event"
let kDressCodeValidation = "Please select dress code for the event"
let kIdValidation = "Please select if ID required for event"
let kEventDescriptionValidation = "Event description must be atleast 2 characters long"
let kStartDateValidation = "Please select start date & time of the event"
let kEndDateValidation = "Please select end date & time of the event"
let kRenewListingValidation = "Please select renew time for event"
let kTicketsValidation = "Please create atleast 1 ticket"
let kTicketNameValidation = "Ticket title must be atleast 2 characters long"
let kTicketDescriptionValidation = "Ticket description must be atleast 2 characters long"
let kTicketAmountValidation = "Please enter ticket amount"
let kTicketQuantityValidation = "Please enter ticket quantity"
let kLoginAlert = "Please login Motiv to proceed"
let kDeleteGuestMessage = "Are you sure you want to remove this guest?"
let kDeleteTicketMessage = "Are you sure you want to remove this ticket?"
let kErrNoQRCodeDetect = "No QR code is detected"
let kTicketCloseMessage = "Tickets have been closed successfully."
let kGuestDeleteMessage = "Guest has been deleted successfully."

//SignupVC
let kNameValidation = "Name must be atleast 2 characters long"
let kUserNameValidation = "Username must be atleast 2 characters long"
let kPhoneValidation = "Please enter valid phone number"
let kDOBValidation = "Please select your date of birth"
let kSignupSuccess = "You have successfully signed up. Please verify your email address to login into the application"
let kSocialSignupSuccess = "You have successfully signed up"
let kDescriptionValidation = "Description must be atleast 4 characters long"



//MARK: **** Popovers ****
let kCreateMotivPop = "Click here to create a MoTiv"
let kScanPop = "Click here to scan tickets"
let kAddGuestPop = "Click here to add a new guest"
let kTicketPop = "Click here to see ticket info"
let kSupportPop = "Click here for support"
let kFilterPop = "Click here to filter your MoTiv"
let kChatPop = "click here for messages"
let kFavouritePop = "Click here to add as favourite"
let kSharePop = "Click here to share"
let kPlayPop = "Click here to play video"

//MARK: **** Common ****
let kNormal = "Normal"
let kFacebook = "Facbook"
let kTwitter = "Twiter"
let kInstagram = "Instagram"
let kPublic = "kPublic"
let kMusic = "kMusic"


//MARK: **** Share Texts ****
